language: java
sudo: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk7
    - os: osx
      osx_image: xcode8.3

addons:
  chrome: stable

before_install:
  - nvm install node
  - npm install
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - mvn package
  - mvn checkstyle:check
  - npm test
  - npm run lint-js
  - npm run lint-md
  - npm run lint-less

after_script: greenkeeper-lockfile-upload

cache:
  directories:
    - $HOME/.m2
    - node_modules
